### ISSUE TITLE
 createjs.StageGL何时可以支持

### ISSUE THREAD

**Issue by cailven** [skyfish-qc/createJs-miniprogram#1]
非常感谢支持了createJs,这下终于可以使用flash导出json动画的功能了，但不知道何时可以支持webgl版的createjs?

**Comment by skyfish-qc** [comment]
webgl版本的放完假再看看了

**Comment by skyfish-qc** [comment]
stageGL已经可以使用，可以查看webgl_example的示例

**Comment by cailven** [comment]
收到太感谢了
