### ISSUE TITLE
原始demo点了十几下后会报错。

### ISSUE THREAD

**Issue by cailven** [skyfish-qc/createJs-miniprogram#2]
![7c7b60a757a63424f43a75c4aff694c](https://user-images.githubusercontent.com/4739001/94392075-d9bb2500-0189-11eb-943e-feb30ee60d4a.jpg)

**Comment by skyfish-qc** [comment]
多次点击让代码以为是进入了一个死循环报错了。。

**Comment by skyfish-qc** [comment]
这个问题已修复，主要是在监听到点击事件时候需要移除，否则就一直重复添加导致出现多次嵌套调用了

**Comment by cailven** [comment]
> 这个问题已修复，主要是在监听到点击事件时候需要移除，否则就一直重复添加导致出现多次嵌套调用了

好的谢谢，非常期待wgl版的createjs.
