### ISSUE TITLE
给元素添加点击事件无效

### ISSUE THREAD

**Issue by oddjohn** [skyfish-qc/createJs-miniprogram#3]
如下，给demo代码的head添加点击无效
`
var head = new createjs.Bitmap("img/head.png");
head.y = 300;
stage.addChild(head);
head.addEventListener('click', () => {
  console.log('点击了')
})
`

**Comment by skyfish-qc** [comment]
已修改

**Comment by oddjohn** [comment]
> 已修改

再求一个webgl的示例

**Comment by skyfish-qc** [comment]
> > 已修改
> 
> 再求一个webgl的示例

webgl的看webgl_example目录里面的例子
